language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
branches:
  only:
    - master
script: coverage run -m unittest edpwd.tests
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - tampakrap@gmail.com
